In [28]:
pip install nibabel

Note: you may need to restart the kernel to use updated packages.


In [58]:
!pwd

from load import load_data
from load import convert_mat

/Users/staceyrivet/Desktop/projects/fmri/fmri/src


ImportError: cannot import name 'convert_mat' from 'load' (/Users/staceyrivet/Desktop/projects/fmri/fmri/src/load.py)

In [57]:
# Load in data from path
#path = '/Users/staceyrivet/Desktop/projects/fmri/fmri/data/ds001_R2.0.4/sub-01/func/sub-01_task-balloonanalogrisktask_run-01_bold.nii.gz'
path = '/Users/staceyrivet/Desktop/projects/fmri/fmri/data/all_data.mat'
mat_data = convert_mat(path)
#img = load_data(path)
mat_data

NameError: name 'convert_mat' is not defined

In [33]:
img.shape


(64, 64, 33, 300)

In [15]:
img.get_data_dtype() == np.dtype(np.int16)

True

In [16]:
""" AFFINE: relating voxel coordinates to world coordinates in RAS+ space 
RAS+ space : RAS+ reference space is a “real-world” space, in the sense that a coordinate in this space refers to a position in the real world
A nibabel (and nipy) image is the association of three things:
The image data array: a 3D or 4D array of image data
An affine array that tells you the position of the image array data in a reference space.
image metadata (data about the data) describing the image, usually in the form of an image header.
This document describes how the affine array describes the position of the image data in a reference space. On the way we will define what we mean by reference space, and the reference spaces that Nibabel uses.
"""

img.affine

array([[  -3.125     ,    0.        ,    0.        ,   99.60421753],
       [   0.        ,    3.125     ,    0.        , -110.1322403 ],
       [   0.        ,    0.        ,    4.        ,  -54.88586807],
       [   0.        ,    0.        ,    0.        ,    1.        ]])

In [18]:
# Get image header information
header = img.header
header.get_xyzt_units()



('mm', 'sec')

In [19]:
print(header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  4  64  64  33 300   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [-1.     3.125  3.125  4.     2.     0.     0.     0.   ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'FSL4.0'
aux_file        : b''
qform_code      : scanner
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : -1.0
quatern_d       : 0.0
qoffset_x       : 97.93152
qoffset_y       : -68.01921
qoffset_z       : -106.6505

In [24]:
# Get numerical data of image in 4D
#image_data = img.get_fdata()
image_data - img.get_data()
image_data # This is the image in 4D

/Users/staceyrivet/Desktop/projects/fmri/venv/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).

* deprecated from version: 3.0
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
  


array([[[[ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         ...,
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0]],

        [[ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         ...,
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0]],

        [[ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         ...,
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0]],

        ...,

        [[ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         ...,
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
    

In [42]:
# This is the image sliced
slice0 = image_data[:, :, :, 0]
#slice1 = image_data[:, :, 1]
slice0.shape





(64, 64, 33)

In [43]:
img_np = np.array(img.dataobj)
img_np

array([[[[ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         ...,
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0]],

        [[ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         ...,
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0]],

        [[ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         ...,
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0]],

        ...,

        [[ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
         ...,
         [ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  0,  0, ...,  0,  0,  0],
    

In [49]:
# num time points
n_time_points = img.shape[-1]
n_time_points

300

In [50]:
# x, y, z of image
img.shape[:-1]

(64, 64, 33)

In [51]:
# get num of voxels
num_voxels = np.prod(img.shape[:-1])
num_voxels



135168

In [52]:
#reshape
voxels_by_time = image_data.reshape((num_voxels, n_time_points))
voxels_by_time

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 6,  9,  7, ..., 10,  6, 10],
       [ 0, 12, 12, ..., 10, 10, 11],
       [11,  5, 11, ..., 22, 11,  4]], dtype=int16)

In [53]:
voxels_by_time.shape



(135168, 300)

In [54]:
#sd of voxels 
std_vox_vec = np.std(voxels_by_time, axis = 0)
std_vox_vec
# need to normalize the data

array([251.77068347, 250.38998082, 249.64439835, 249.54647239,
       249.66197261, 249.7278684 , 250.30226946, 250.5981299 ,
       249.87821407, 250.07907235, 250.33076558, 250.16636433,
       249.59309633, 249.11310184, 250.06763133, 250.6651794 ,
       251.11146917, 250.89402253, 250.70024667, 249.93038465,
       250.09525318, 249.82977952, 249.88712452, 249.43918755,
       249.64259987, 249.84893624, 250.1601299 , 250.31533434,
       251.0835814 , 250.5292549 , 249.95299975, 249.54255293,
       249.79283234, 249.66860919, 250.08266875, 250.44813675,
       250.79485486, 250.36279317, 250.09021214, 249.94252357,
       250.10385226, 249.6712956 , 249.67117126, 249.57401067,
       249.6940415 , 250.13709691, 250.76562257, 250.62667168,
       250.09352995, 250.21436906, 249.97271882, 249.98502755,
       250.34852043, 250.52912016, 250.75986357, 250.39794181,
       250.28833906, 249.97119989, 250.06761909, 250.20144598,
       250.70806412, 250.58387225, 250.42221122, 250.18